pub mod day_1_trebuchet;
pub mod day_2_cube_conundrum;
pub mod day_3_gear_ratios;
pub mod day_4_scratchcards;
pub mod day_5_if_you_give_a_seed_a_fertilizer;
pub mod day_6_wait_for_it;
pub mod day_7_camel_cards;
pub mod day_8_haunted_wasteland;
pub mod day_9_mirage_maintenance;
